name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      workDir: ./AwesomeApp/
      AZURE_WEBAPP_NAME: agilesedq    # set this to your application's name      
      DOTNET_VERSION: '3.1.x'         # set this to the dot net version to use:  

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.workDir}}
    - name: Build
      working-directory: ${{env.workDir}}
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ${{env.workDir}}
      run: dotnet test --no-restore --verbosity normal
    - name: Create Release
      working-directory: ${{env.workDir}}
      run: dotnet publish -c Release -o 'myapp'
    
    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'      
      uses: azure/webapps-deploy@v2      
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.workDir }}/myapp'
